project:
  type: website

website:
  title: "playing-with-queues"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/wzbillings
      - icon: house-door-fill
        href: https://wzbillings.com
format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css



